<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="NARUTO-UZUMAKI" failures="1" tests="5" name="Default test(failed)" time="0.101" errors="0" timestamp="2023-08-29T20:17:30 IST">
  <testcase classname="TestNG.CustomerModule" name="createCustomer" time="0.017"/>
  <testcase classname="TestNG.CustomerModule" name="createCustomer" time="0.003"/>
  <testcase classname="TestNG.CustomerModule" name="createCustomer" time="0.003"/>
  <testcase classname="TestNG.CustomerModule" name="modifyCustomer" time="0.005">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TestNG.CustomerModule.modifyCustomer(CustomerModule.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- modifyCustomer -->
  <testcase classname="TestNG.CustomerModule" name="deleteCustomer" time="0.002">
    <skipped/>
  </testcase> <!-- deleteCustomer -->
</testsuite> <!-- Default test(failed) -->
